# Generated by Django 3.2.16 on 2023-06-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cocktail_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='glass',
            field=models.CharField(default='rocks', max_length=255),
        ),
    ]
